name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.3.0
  firebase_core: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add custom fonts here
  fonts:
    - family: Saking
      fonts:
        - asset: assets/fonts/saking.otf

    - family: Performa
      fonts:
        - asset: assets/fonts/performa-nr-extrabold.ttf

  # Add image assets here
  assets:
    - assets/images/4leafclover.png
    - assets/images/onlyin_hlck/white_logo.png
    - assets/images/onlyin_hlck/white_logo1.png
