name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8  
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.3.0
  firebase_core: ^3.13.1
  provider: ^6.1.2
  firebase_database: ^11.3.6
  firebase_storage: ^12.4.6
  image_picker: ^1.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Saking
      fonts:
        - asset: assets/fonts/saking.otf

    - family: Performa
      fonts:
        - asset: assets/fonts/performa-nr-extrabold.ttf

  assets:
    - assets/images/
    - assets/images/onlyin_hlck/
    - assets/images/plain/
    - assets/images/graphic_tee/
    - assets/images/hoodie/