// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJOkpGSg3upXVt7SKDB8l0NV7TKHOSSYw',
    appId: '1:427771018:web:e6ba9e5fb511d2b05d9973',
    messagingSenderId: '427771018',
    projectId: 'finalproject-91acc',
    authDomain: 'finalproject-91acc.firebaseapp.com',
    storageBucket: 'finalproject-91acc.firebasestorage.app',
    measurementId: 'G-YYJV1ZHJKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8PSIUKE3ZUnndvAU_Gk6yjkg_UGjYo18',
    appId: '1:427771018:android:251ed1aa346ae0e65d9973',
    messagingSenderId: '427771018',
    projectId: 'finalproject-91acc',
    storageBucket: 'finalproject-91acc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2YLbbErl5bZNznf9K1NNr6ItFuclQAyM',
    appId: '1:427771018:ios:eb69d2c855f659d85d9973',
    messagingSenderId: '427771018',
    projectId: 'finalproject-91acc',
    storageBucket: 'finalproject-91acc.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2YLbbErl5bZNznf9K1NNr6ItFuclQAyM',
    appId: '1:427771018:ios:eb69d2c855f659d85d9973',
    messagingSenderId: '427771018',
    projectId: 'finalproject-91acc',
    storageBucket: 'finalproject-91acc.firebasestorage.app',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJOkpGSg3upXVt7SKDB8l0NV7TKHOSSYw',
    appId: '1:427771018:web:8fa6b85cf152e52b5d9973',
    messagingSenderId: '427771018',
    projectId: 'finalproject-91acc',
    authDomain: 'finalproject-91acc.firebaseapp.com',
    storageBucket: 'finalproject-91acc.firebasestorage.app',
    measurementId: 'G-RZSHM2VLXK',
  );
}
